apiVersion: v1
kind: ConfigMap
metadata: { name: configmap-recycle }
data:
  QDRANT_URL: "http://qdrant:6333"
  QDRANT_COLLECTION: "recycle_docs"
  EMBED_MODEL: "text-embedding-3-small"
  MIN_SCORE: "0.55"
  TOP_K: "5"