apiVersion: apps/v1
kind: Deployment
metadata:
  name: embedchat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: embedchat
  template:
    metadata:
      labels:
        app: embedchat
    spec:
      containers:
        - name: embedchat
          image: recycle-embed-chat:latest
          imagePullPolicy: Never
          envFrom:
            - secretRef:
                name: secret-openai
            - configMapRef:
                name: configmap-recycle
          stdin: true
          tty: true
          command: ["bash","-lc","python recycle_agent.py"]